config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  # The priority is based   upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".
    resources :location, :users
  # You can have the root of your site routed with "root"
  root 'home#index'
  get 'careers/' => 'careers#index'
  get 'careers/application' => 'careers#application'
  post 'careers/application' => 'careers#application'
  get 'careers/application/:id' => 'careers#show'
  get 'location/index'
  get '/about' => 'home#about'
  post '/about' => 'home#about'
  get '/finance' => 'home#finance'
  get '/contactus' => 'home#contactus'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
    
    
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/career.rb
class Career < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    validates(:username, presence: true, uniqueness: true)
    
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    def about
        render header
    end
    
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  def index
  end
  def application
  end
  def create
    @career = Career.new(career_params)
    if @career.save
        redirect_to @career
    else
        render 'new'
    end
  end
  def new
    @career = Career.new
  end
    
  private
    def career_params
        params.require(:career).permit(:first, :last, :submitDate, :phone, :email, :info)
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
    
  def location
  end
    
  def about
     
  end
  def finance
  end
  def contactus
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
    def index
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
    def create
        render 'new'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
  end
    def index
    end
    def create
        @user = User.new(params[:user])
    end
    def show
        @user = User.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/careers/application.html.erb
<html>
    <%= render "layouts/header" %>
    <div class="container">
        <p class="lead">Application</p>
        <%= form_for :career do |c| %>
     
        <%= c.text_field :first_name, :class => "form-control", :placeholder => "First name"%>
        <br>
        <%= c.text_field :last_name, :class => "form-control", :placeholder => "Last name"%>
        <br>
        <%= c.text_field :email, :class => "form-control", :placeholder => "E-mail" %>
        <br>
        <%= c.submit :Submit, :class => "btn btn-default navbar-btn"%>
        <br>
        <% end %>
    </div>

</html>

app/views/careers/index.html.erb
<html>
<%= render "layouts/header" %>
    <div class="container">
        <h1 class="cover-heading">Careers</h1>
        <p class="lead">At MetroPCS No Limit Talk, we are always looking for people to...</p>
        
    <p>Careers</p>
        
<p>Find me in app/views/careers/index.html.erb</p>
        <%= link_to "Apply", careers_application_path, :class => "btn btn-default navbar-btn" %>
</div>
</html>

app/views/careers/show.html.erb
<h1>show Career</h1>

app/views/home/about.html.erb
<html>
<body>
    <%= render "layouts/header" %>
    <div class="container">
    <p> ABOUT </p>
    </div>
</body>
</html>

app/views/home/contactus.html.erb
<html>
<body>
    <%= render "layouts/header" %>
    <div class="container">
<p>Contact us</p>
    </div>
    </body>
    
</html>

app/views/home/finance.html.erb
<html>
<%= render "layouts/header" %>
    <div class="container">
        <h1 class="cover-heading">Financing</h1>
        <p class="lead">Hi</p>
        <p class="lead">Bye</p>
    </div>
</html>

app/views/home/index.html.erb
<html>
    <body>

    <%= render "layouts/header" %>
<div class="container">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>


      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
            <%= image_tag "Image_Coverage.png" %>
        </div>  
        <div class="item">
            <%= image_tag "B-spot-Riding.jpg" %>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
</div>
    </body>
    
</html>

app/views/home/location.html.erb
<h1>Location page</h1>

app/views/layouts/_footer.html.erb
<%= stylesheet_link_tag "application" %>
<%= javascript_include_tag "application" %>
<html>
    <div class="container">
<div class="panel-footer">
Footer
</div>
    </div>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag "application" %>
<%= javascript_include_tag "application" %>
<div class="container">
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="">MetroPCS - No Limit Talk</a>
        </div> 
        
        <div class="collapse navbar-collapse" id="header-navbar-collapse">
        <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'Location', location_index_path %></li>
            <li><%= link_to 'Finance', finance_path %></li>
            <li><%= link_to 'Careers', careers_path %></li>
            <li><%= link_to 'Contact', contactus_path %></li>
        </ul>
        <%= button_to 'Sign in', login_path, :class => "btn btn-default navbar-btn" %>
        </div>
    </div>  
</nav>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MetroPCSRuby</title>
</head>
<body>

<%= yield %>
</body>
</html>

app/views/location/index.html.erb
<html>
    <body>
    <%= render "layouts/header" %>
    </body>
    <div class="container">
    <p>The lovely location page. Map coming soon</p>
    </div>
</html>

app/views/users/index.html.erb
<html>

    <%= render 'layouts/header' %>
    <div class="container">
    <p>
    User index
    </p>
    </div>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
<div class="row">
<aside class="col-md-4">
<section class="user_info">
<h1>
    <%= @user.name %>
</h1>
</section>
</aside>    
</div>

</div>